Make `h2o_httpclient__tunnel_is_ready` `static inline`
Not doing so breaks the compilation of standalone programs that include `h2o.h`:
```
/usr/bin/ld: /tmp/ccghrRPU.o: warning: relocation against `h2o_httpclient_upgrade_to_connect' in read-only section `.text'
/usr/bin/ld: /tmp/ccghrRPU.o: in function `h2o_httpclient__tunnel_is_ready':
test.c:(.text+0x29): undefined reference to `h2o_httpclient_upgrade_to_connect'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
```